version: "3"
services:
    db:
      container_name: lisn_database
      image: postgres:13-alpine
      env_file:
        - .env
      ports:
        - 5432:5432
      volumes:
        - ./sql/00001-init-tables.sql:/docker-entrypoint-initdb.d/init.sql
