#!/usr/bin/bash


# Create the root folder at `~/Public/lisn`.
mkdir root root/logs root/storage root/storage/albums root/storage/songs
cp -r .pkg/pub root/

# The `root/pub/lisn` folder and everything within, will be generated by
# `npm run build` from lisn-web-app folder ... given you set it up properly :)
# See: https://github.com/sharpvik/lisn-web-app

if [ ! -d ~/Public ]; then
    mkdir ~/Public
fi
mv root ~/Public/lisn


# Unpack config files .You'll have to edit these!
cp -r .pkg/config config